### PR TITLE
Fix #172: Replace SQL NOW by parameter

### LINKED ISSUE #172: Use SQL parameter for now function
### Affected product(s) and version(s)

_No response_

### Environment

_No response_

### Steps to reproduce, current result, expected result

In some SQL queries we use `NOW()`. This doesn't work for Oracle because such function doesn't exist in database. We should pass now as parameter to SQL query

### Log output

OracleDatabaseException: ORA-00904: "NOW": invalid identifier

### PR DESCRIPTION
**Pull request by michal-rozehnal-w**

### CODE REVIEW

File: signer-cloud-server/src/main/java/com/wultra/signercloud/server/signer/IssuedCertificateMetadataRepository.java [hunk 1]
```diff
@@ -29,9 +30,16 @@
  */
 interface IssuedCertificateMetadataRepository extends CrudRepository<IssuedCertificateMetadata, Long> {
 
+    /**
+     * Finds all active issued certificates for the signer.
+     *
+     * @param signerId id of Signer to be revocated
```
[the remark this answers is not in the document]
Comment (michal-rozehnal-w) [reply signer-cloud-server/src/main/java/com/wultra/signercloud/server/signer/IssuedCertificateMetadataRepository.java]: Fixed

File: signer-cloud-server/src/main/java/com/wultra/signercloud/server/signer/IssuedCertificateMetadataRepository.java [hunk 2]
```diff
@@ -29,9 +30,16 @@
...
+     * @param now Current time
+     * @return list of certificates metadata
+     */
     @Query("""
         SELECT * FROM "sc_issued_certificate_metadata"
-        WHERE "signer_id" = :signerId AND "timestamp_certificate_expiration" > NOW() AND "status" != 'REVOKED'
+        WHERE "signer_id" = :signerId AND "timestamp_certificate_expiration" > :now AND "status" != 'REVOKED'
         """)
-    List<IssuedCertificateMetadata> findForRevocation(final long signerId);
+    List<IssuedCertificateMetadata> findForRevocation(final long signerId, final Instant now);
```
Comment (banterCZ) [inline signer-cloud-server/src/main/java/com/wultra/signercloud/server/signer/IssuedCertificateMetadataRepository.java:44]: Nitpick: sometimes we have `now` as the first parameter, some is the last.

File: signer-cloud-server/src/main/java/com/wultra/signercloud/server/signer/SignerRepository.java [hunk 3]
```diff
@@ -38,44 +38,47 @@ public interface SignerRepository extends CrudRepository<Signer, Long> {
...
      * @implSpec {@code FETCH FIRST} is supported by {@code ANSI SQL:2008}.
      */
     @Query("""
-        SELECT * FROM "sc_signer" WHERE "status" = 'ACTIVE' AND "timestamp_certificate_expiration" BETWEEN NOW() AND :expirationThreshold
+        SELECT * FROM "sc_signer" WHERE "status" = 'ACTIVE' AND "timestamp_certificate_expiration" BETWEEN :now AND :expirationThreshold
                 ORDER BY "timestamp_certificate_expiration"
                 FETCH FIRST :limit ROWS ONLY
         """)
-    List<Signer> findForRenewal(Instant expirationThreshold, int limit);
+    List<Signer> findForRenewal(final Instant now, final Instant expirationThreshold, final int limit);
```
Comment (banterCZ) [inline signer-cloud-server/src/main/java/com/wultra/signercloud/server/signer/SignerRepository.java]: This is tricky. Two parameters of the same type in the row.

**Review by banterCZ — APPROVED** [review]
Thanks for the fix.

File: signer-cloud-server/src/main/java/com/wultra/signercloud/server/signer/IssuedCertificateMetadataRepository.java (hunk 2 above)
Comment (michal-rozehnal-w) [reply signer-cloud-server/src/main/java/com/wultra/signercloud/server/signer/IssuedCertificateMetadataRepository.java:44]: Yes, I respected order params in the SQL query. But I can put `now` always as last parameter

File: signer-cloud-server/src/main/java/com/wultra/signercloud/server/signer/SignerRepository.java (hunk 3 above)
Comment (michal-rozehnal-w) [reply signer-cloud-server/src/main/java/com/wultra/signercloud/server/signer/SignerRepository.java]: Good point, I can move the `now` as last parametr (as mentioned in previous comment). In this way they at lest won't be in the row
